version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dine_line
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    command: redis-server --requirepass pass
    ports:
      - 6379:6379
