version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dine_line
    command: -p 5050
    ports:
      - 5050:5050
  redis:
    image: redis:alpine
    command: redis-server --requirepass pass
    ports:
      - 6379:6379
